[Interface]
Address = 192.168.99.1/24
ListenPort = 51820
PrivateKey = SC84zrhzeGqFiHfzBHSxbaeFpIi0ju8FppQRRLibTVg=

[Peer]
PublicKey = 6YSmNHEnsilzL9rH8nk77Zz9/6Sdf8gUAGI73SD1Ego=
AllowedIPs = 192.168.99.2/32
Endpoint = 120.229.70.151:8298

[Peer]
PublicKey = EtRuDtKW2BrZNTYvlc5XAEJzIdtyksJmIIHzfyuKXGI=
AllowedIPs = 192.168.99.3/32
